import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { SUPABASE_CONFIG, isSupabaseConfigured } from './supabase.config';

// Try environment variables first (if available), then fall back to config file
const supabaseUrl = 
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_URL) || 
  (typeof process !== 'undefined' && process.env?.REACT_APP_SUPABASE_URL) || 
  SUPABASE_CONFIG.url;

const supabaseAnonKey = 
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_ANON_KEY) || 
  (typeof process !== 'undefined' && process.env?.REACT_APP_SUPABASE_ANON_KEY) || 
  SUPABASE_CONFIG.anonKey;

// Warn if Supabase is not configured
if (!isSupabaseConfigured()) {
  console.warn(`
╔════════════════════════════════════════════════════════════════════════╗
║                   ⚠️  SUPABASE NOT CONFIGURED                         ║
╚════════════════════════════════════════════════════════════════════════╝

To set up authentication:

📝 UPDATE THIS FILE: /lib/supabase.config.ts

1. Open /lib/supabase.config.ts
2. Replace the placeholder values with your Supabase credentials
3. Save the file

Get your credentials from: https://app.supabase.com
→ Select your project
→ Settings > API
→ Copy "Project URL" and "anon public" key

For detailed setup instructions, see:
→ /IMPLEMENTATION_STEPS.md
→ /README_SETUP.md
`);
}

// Create a single supabase client for interacting with your database
// Uses placeholder values if not configured (prevents crash during development)
export const supabase: SupabaseClient = createClient(
  supabaseUrl || 'https://placeholder.supabase.co', 
  supabaseAnonKey || 'placeholder-key',
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
  }
);

// Database types (will be auto-generated by Supabase CLI in production)
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string;
          is_2fa_enabled: boolean;
          has_seen_onboarding: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email: string;
          is_2fa_enabled?: boolean;
          has_seen_onboarding?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string;
          is_2fa_enabled?: boolean;
          has_seen_onboarding?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

export type Profile = Database['public']['Tables']['profiles']['Row'];
